apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-website
  template:
    metadata:
      labels:
        app: portfolio-website
    spec:
      containers:
        - name: portfolio-website
          image: localhost:5000/portfolio-website:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
   name: po-entrypoint
   namespace: default
spec:
   type: NodePort
   selector:
      app: portfolio-website  # Match the label defined in the Deployment
   ports:
      - port: 3000
        targetPort: 3000
        nodePort: 30001  # Make sure this port is within the allowed NodePort range