name: Build and Deploy React App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build the app
      run: npm run build

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Deploy to gh-pages
      run: |
        git --work-tree build add --all
        git commit -m "Automatic Build and Deploy run by GitHub Actions"
        git push origin HEAD:gh-pages --force
