name: Build and Deploy React app
description: 'GitHub Action to build and deploy React app in gh-pages branch.'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Build and Deploy React app to GitHub Pages
      uses: omkartapale/react-deployment-gh-pages@v1.0.0

    - run : npm install --legacy-peer-deps
    - run : npm --legacy-peer-deps
    - run : npm run build
    - run : git config user.name github-actions
    - run : git config user.email github-actions@github.com
    - run : git --work-tree build add --all
    - run : git commit -m "Automatic Build and Deploy run by GitHub Actions"
    - run : git push origin HEAD:gh-pages --force