name: Build and Deploy React App

on:
  push:
    branches: [ "master" ]

jobs:
  deploy-react-to-gh-pages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18.16.1"

      # install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # build the react app
      - name: Build the app
        run: npm run build

      #deploy the react app to github pages
      - name: Deploy🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build